server:
  port: 8080

spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      label: main
      profile: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO
    com.example.demo: DEBUG